"""Differential harness for the FFI path: native avr-gcc vs cc1/cc1plus on wasm.

Runs the full C/C++ interop pipeline both ways and compares the .hex by sha256:

    cc1 / cc1plus   .c/.cpp -> .s
    avr-as          .s      -> .o
    avr-as          firmware.gas.asm -> firmware.o
    avr-ld          everything -> .elf
    avr-objcopy     .elf -> .hex

The per-chip cc1 flags come from cc1_flags.json, generated by asking
`avr-gcc -mmcu=<chip> -###`.
"""

from __future__ import annotations

import hashlib
import json
import shutil
import subprocess
import sys
import time
from pathlib import Path

from wasmtime import Engine, ExitTrap, Linker, Module, Store, WasiConfig

HERE = Path(__file__).resolve().parent
NATIVE = HERE / "native" / "pymcu_avr_toolchain"
EXAMPLES = Path.home() / "Repos" / "pymcu-avr" / "examples"
GCC_VER = "14.2.0"
SYSROOT_FFI = HERE / "sysroot-ffi"

MODULES = {
    "avr-as": HERE / "dist" / "avr-as.wasm",
    "avr-ld": HERE / "dist" / "avr-ld.wasm",
    "avr-objcopy": HERE / "dist" / "avr-objcopy.wasm",
    "cc1": HERE / "dist-ffi" / "cc1.wasm",
    "cc1plus": HERE / "dist-ffi" / "cc1plus.wasm",
}

FLAGS = json.loads((HERE / "cc1_flags.json").read_text())
CPP_SUFFIXES = {".cpp", ".cc", ".cxx", ".C"}


class Wasm:
    def __init__(self) -> None:
        self.engine = Engine()
        self.linker = Linker(self.engine)
        self.linker.define_wasi()
        cache = HERE / ".cwasm-ffi"
        cache.mkdir(exist_ok=True)
        self.modules = {}
        for name, path in MODULES.items():
            cached = cache / f"{name}.cwasm"
            if cached.exists() and cached.stat().st_mtime >= path.stat().st_mtime:
                self.modules[name] = Module.deserialize_file(self.engine, str(cached))
            else:
                mod = Module.from_file(self.engine, str(path))
                cached.write_bytes(mod.serialize())
                self.modules[name] = mod

    def run(self, tool: str, argv: list[str], preopens: list[tuple[Path, str]]) -> None:
        import tempfile

        with tempfile.TemporaryDirectory() as tmp:
            out, err = Path(tmp) / "o", Path(tmp) / "e"
            cfg = WasiConfig()
            cfg.argv = [tool, *argv]
            for host, guest in preopens:
                cfg.preopen_dir(str(host), guest)
            cfg.stdout_file, cfg.stderr_file = str(out), str(err)
            store = Store(self.engine)
            store.set_wasi(cfg)
            code = 0
            try:
                inst = self.linker.instantiate(store, self.modules[tool])
                inst.exports(store)["_start"](store)
            except ExitTrap as exc:
                code = exc.code
            del store
            msg = (err.read_bytes().decode(errors="replace") if err.exists() else "")
            msg += (out.read_bytes().decode(errors="replace") if out.exists() else "")
        if code != 0:
            raise RuntimeError(f"{tool} exit {code}: {msg[:400]}")


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def native_build(example: Path, work: Path, chip: str, emu: str, multilib: str,
                 sources: list[Path], incdirs: list[Path], cflags: list[str]) -> Path:
    work.mkdir(parents=True, exist_ok=True)
    shutil.copy(example / "dist" / "debug" / "firmware.asm", work / "firmware.asm")
    shutil.copy(example / "dist" / "_pymcu.ld", work / "_pymcu.ld")
    bin_ = NATIVE / "bin"

    objs = []
    for src in sources:
        obj = work / (src.stem + ".o")
        is_cpp = src.suffix in CPP_SUFFIXES
        cc = bin_ / ("avr-g++" if is_cpp else "avr-gcc")
        extra = ["-fno-exceptions", "-fno-rtti", "-std=c++17"] if is_cpp else []
        subprocess.run(
            [str(cc), f"-mmcu={chip}", "-Os", "-c", *extra, *cflags,
             *[f"-I{d}" for d in incdirs], str(src), "-o", str(obj)],
            check=True, capture_output=True)
        objs.append(obj)

    subprocess.run([str(bin_ / "avr-as"), f"-mmcu={chip}", "-mno-skip-bug",
                    "firmware.asm", "-o", "firmware.o"],
                   cwd=work, check=True, capture_output=True)
    subprocess.run([str(bin_ / "avr-ld"), f"-m{emu}", "-Tdata", "0x800100", "--relax",
                    "-o", "firmware.elf",
                    f"-L{NATIVE / 'lib' / 'gcc' / 'avr' / GCC_VER / multilib}",
                    f"-L{NATIVE / 'avr' / 'lib' / multilib}",
                    "firmware.o", *[o.name for o in objs], "-lm", "-lgcc",
                    "-T", "_pymcu.ld"],
                   cwd=work, check=True, capture_output=True)
    subprocess.run([str(bin_ / "avr-objcopy"), "-O", "ihex", "-R", ".eeprom",
                    "firmware.elf", "firmware.hex"],
                   cwd=work, check=True, capture_output=True)
    return work / "firmware.hex"


def wasi_build(wasm: Wasm, example: Path, work: Path, chip: str, emu: str, multilib: str,
               sources: list[Path], incdirs: list[Path], cflags: list[str]) -> Path:
    work.mkdir(parents=True, exist_ok=True)
    shutil.copy(example / "dist" / "debug" / "firmware.asm", work / "firmware.asm")
    shutil.copy(example / "dist" / "_pymcu.ld", work / "_pymcu.ld")
    libdir = work / "lib"
    libdir.mkdir(exist_ok=True)
    shutil.copy(NATIVE / "lib" / "gcc" / "avr" / GCC_VER / multilib / "libgcc.a", libdir)
    shutil.copy(NATIVE / "avr" / "lib" / multilib / "libm.a", libdir)

    src_dir = work / "src"
    src_dir.mkdir(exist_ok=True)
    for extra_dir in incdirs:
        for header in extra_dir.glob("*.h"):
            shutil.copy(header, src_dir / header.name)

    chip_flags = FLAGS[chip]["flags"]
    objs = []
    for src in sources:
        shutil.copy(src, src_dir / src.name)
        is_cpp = src.suffix in CPP_SUFFIXES
        tool = "cc1plus" if is_cpp else "cc1"
        extra = (["-fno-exceptions", "-fno-rtti", "-std=c++17"] if is_cpp else [])
        asm = f"/work/{src.stem}.s"
        wasm.run(tool, [
            "-quiet", "-nostdinc",
            "-isystem", "/inc/gcc", "-isystem", "/inc/gcc-fixed", "-isystem", "/inc/avr",
            "-I", "/work/src",
            *chip_flags, "-mno-skip-bug", "-Os", *cflags, *extra,
            f"/work/src/{src.name}", "-o", asm,
        ], [(work, "/work"), (SYSROOT_FFI, "/inc")])

        obj = f"{src.stem}.o"
        wasm.run("avr-as", [f"-mmcu={chip}", "-mno-skip-bug",
                            asm, "-o", f"/work/{obj}"], [(work, "/work")])
        objs.append(obj)

    wasm.run("avr-as", [f"-mmcu={chip}", "-mno-skip-bug",
                        "/work/firmware.asm", "-o", "/work/firmware.o"], [(work, "/work")])
    wasm.run("avr-ld", [f"-m{emu}", "-Tdata", "0x800100", "--relax",
                        "-o", "/work/firmware.elf", "-L/work/lib",
                        "/work/firmware.o", *[f"/work/{o}" for o in objs],
                        "-lm", "-lgcc", "-T", "/work/_pymcu.ld"], [(work, "/work")])
    wasm.run("avr-objcopy", ["-O", "ihex", "-R", ".eeprom",
                             "/work/firmware.elf", "/work/firmware.hex"], [(work, "/work")])
    return work / "firmware.hex"


def ffi_config(example: Path) -> tuple[list[Path], list[Path], list[str]]:
    text = (example / "pyproject.toml").read_text()
    try:
        import tomllib
    except ImportError:
        import tomli as tomllib
    data = tomllib.loads(text)
    ffi = data.get("tool", {}).get("pymcu", {}).get("ffi", {})
    sources = [example / s for s in ffi.get("sources", [])]
    incdirs = [example / d for d in ffi.get("include_dirs", [])]
    cflags = [f for f in ffi.get("cflags", []) if f not in ("-Os",)]
    return sources, incdirs, cflags


def chip_of(example: Path) -> str:
    for line in (example / "pyproject.toml").read_text().splitlines():
        if line.strip().startswith("target"):
            return line.split("=", 1)[1].strip().strip('"')
    return "atmega328p"


def main() -> int:
    from pymcu_wasi_toolchain import sha256 as _  # noqa: F401  (same helper, keep import cheap)

    root = HERE / "t" / "ffi"
    shutil.rmtree(root, ignore_errors=True)
    wasm = Wasm()

    targets = sorted(p for p in EXAMPLES.iterdir()
                     if (p / "pyproject.toml").exists()
                     and "[tool.pymcu.ffi]" in (p / "pyproject.toml").read_text()
                     and (p / "dist" / "debug" / "firmware.asm").exists())
    extra = HERE / "t" / "cpp-case"
    if extra.exists():
        targets.append(extra)

    ok = bad = skipped = 0
    t_native = t_wasi = 0.0
    for example in targets:
        chip = chip_of(example)
        emu = FLAGS[chip]["flags"]
        emu = next(f.split("=")[1] for f in emu if f.startswith("-mmcu="))
        multilib = FLAGS[chip]["multilib"]
        sources, incdirs, cflags = ffi_config(example)
        if not sources:
            skipped += 1
            continue
        try:
            t0 = time.perf_counter()
            n_hex = native_build(example, root / example.name / "native", chip, emu,
                                 multilib, sources, incdirs, cflags)
            t_native += time.perf_counter() - t0
        except subprocess.CalledProcessError as exc:
            skipped += 1
            print(f"SKIP  {example.name}: nativo -> {exc.stderr.decode()[:120].strip()}")
            continue
        try:
            t0 = time.perf_counter()
            w_hex = wasi_build(wasm, example, root / example.name / "wasi", chip, emu,
                               multilib, sources, incdirs, cflags)
            t_wasi += time.perf_counter() - t0
        except RuntimeError as exc:
            bad += 1
            print(f"FAIL  {example.name}: {exc}")
            continue

        if sha256(n_hex) == sha256(w_hex):
            ok += 1
            print(f"same  {example.name:<14} {sha256(n_hex)[:16]}")
        else:
            bad += 1
            print(f"DIFF  {example.name:<14} nativo={sha256(n_hex)[:16]} wasi={sha256(w_hex)[:16]}")

    print()
    print(f"identicos={ok}  distintos/fallidos={bad}  saltados={skipped}")
    print(f"tiempo  nativo {t_native:.2f}s   wasi {t_wasi:.2f}s")
    return 0 if bad == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
